### PR TITLE
feat: Remove anvil renaming cost

### PR DESCRIPTION
**Pull request by CoolandonRS**
What it says on the tin.
fixes: https://github.com/Yarden-zamir/Create-Prepare-to-Dye/issues/409

### CODE REVIEW

**Comment by CoolandonRS** [comment]
Do test this, there is a 90% chance it works but it still might not

**Comment by jasperalani** [comment]
waiting for https://github.com/game-design-driven/Create-Prepare-to-Dye/pull/517 to be accepted then will test this

**Comment by jasperalani** [comment]
Hey @CoolandonRS would you mind adding comments to all the functions and the class and stuff otherwise in the future it might be hard to understand whats going on

**Comment by CoolandonRS** [comment]
Yeah I suppose. It's already going to be hard to understand because it is just reflection witchery but I'll add some to try to help out.

**Comment by jasperalani** [comment]
I can't get it to work sadly. Did you not test it yourself?

**Comment by CoolandonRS** [comment]
No, I didn't test it since I couldn't get `gradle runClient` to work and didn't want to debug it at the time. Now that I already have I'll debug it some more and see if I can verify it works/create a new (functioning) solution

**Comment by CoolandonRS** [comment]
And actually I think I already see the problem. We `reobf` the jar which changes the names of fields when compiled, and since we are using reflection that's mildly unfortunate at times. I'll double check this theory and fix it, or theoretically yarn intermediaries mean that it'll be constant and we can simply reference the intermediary value instead.

**Comment by CoolandonRS** [comment]
Replaced by #12

**Pull request closed without merging**
