### PR TITLE
feat: Remove Anvil renaming cost via mixin 

### PR DESCRIPTION
**Pull request by CoolandonRS**
What it says on the tin.
fixes https://github.com/game-design-driven/Create-Prepare-to-Dye/issues/409

### CODE REVIEW

**Comment by CoolandonRS** [comment]
Put as a draft PR since I've hit a bit wall, will work circle back around to it when I remember (hopefully tomorrow). Feel free to mention me somewhere if I don't come back to remind me so I can get back on it.

@EngineerSmith given you wrote the other mixins you might want to give this a shot to figure out why it isn't quite cooperating (depending on how familiar you are with mixins)

**Comment by jasperalani** [comment]
I think the block is missing texture still. other than that looking good

**Comment by CoolandonRS** [comment]
@Yarden-zamir did mention they'd rather this be entirely unique from an anvil, so if we go that route it will need quite a bit more work before completion. 

Either way, should definitely get an art contributor on the texture given I'm no good at that.

**Comment by CoolandonRS** [comment]
Lesson learned, merging with upstream through my IDE causes github to have a stroke, so doing it through github is just the better way to do it.

**Comment by jasperalani** [comment]
I've messed something up with the build script, gonna have a look tmrw everything paused tonight.

**Comment by jasperalani** [comment]
merging this into a new feature branch, im going to add a command that opens the anvil clone

**Pull request merged**
